### ISSUE TITLE
Remove obj & bin directories

### ISSUE THREAD

**Issue by MaxWasUnavailable** [CMDR-3/ModdersToolKit#1]
Hi there! It seems you pushed your obj & bin directories. These contain assemblies you're not allowed to distribute.

https://github.com/CMDR-3/ModdersToolKit/tree/main/ModdersToolKit/bin/Debug
https://github.com/CMDR-3/ModdersToolKit/tree/main/ModdersToolKit/obj/Debug

**Comment by CMDR-3** [comment]
Oops that would be my bad. They have since been deleted.
